kind: Deployment
apiVersion: apps/v1
metadata:
  name: elephant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elephant
  template:
    metadata:
      labels:
        app: elephant
    spec:
      containers:
        - name: elephant
          image: gcr.io/blueforest/pastistech2_elephant
          ports:
            - containerPort: 8080
